// svelte-vs-react/01-svelte/src/08-context/components/login.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { loop_guard } from "svelte/internal";
  import { Writable } from "svelte/store";

  const user: Writable<string> = getContext("user-info");
</script>

<h2>Enter your name:</h2>
<input type="text" value={$user} on:input={(e) => user.set(e.target.value)} />

// svelte/svelte-vs-react/00-react/src/07-common-data/components/login.tsx
import React from "react";
import { MyContext } from "../context/user.context";

export const Login = () => {
  const myContext = React.useContext(MyContext);

  return (
    <>
      <h3>Enter your name:</h3>
      <input
        type="text"
        value={myContext.username}
        onChange={(e) => myContext.setUsername(e.target.value)}
      />
    </>
  );
};
